/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EBtnTheme: typeof import('./../components/button/EBtnTheme.vue')['default']
    EIcon: typeof import('./../components/common/EIcon.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElementLayout: typeof import('./../layouts/ElementLayout/ElementLayout.vue')['default']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyPage: typeof import('./../components/page/EmptyPage.vue')['default']
    ErrorLayout: typeof import('./../layouts/ErrorLayout.vue')['default']
    MainHeader: typeof import('./../layouts/ElementLayout/MainHeader/MainHeader.vue')['default']
    MainHeaderTabItem: typeof import('./../layouts/ElementLayout/MainHeader/MainHeaderTabItem.vue')['default']
    MainHeaderTabs: typeof import('./../layouts/ElementLayout/MainHeader/MainHeaderTabs.vue')['default']
    MainHeaderUser: typeof import('./../layouts/ElementLayout/MainHeader/MainHeaderUser.vue')['default']
    MainLayout: typeof import('./../layouts/MainLayout.vue')['default']
    QuasarLayout: typeof import('./../layouts/QuasarLayout/QuasarLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterPage: typeof import('./../components/page/RouterPage.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
