/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppPage: typeof import('./../components/page/AppPage.vue')['default']
    EBreadcrumb: typeof import('./../components/page/AppPage/EBreadcrumb.vue')['default']
    EBtn: typeof import('./../components/button/EBtn.vue')['default']
    EBtnFullscreen: typeof import('./../components/button/EBtnFullscreen.vue')['default']
    EBtnIcon: typeof import('./../components/button/EBtnIcon.vue')['default']
    EBtnTheme: typeof import('./../components/button/EBtnTheme.vue')['default']
    EDialog: typeof import('./../components/dialog/EDialog.vue')['default']
    EDialogSetting: typeof import('./../components/dialog/EDialogSetting.vue')['default']
    EDropdownItem: typeof import('./../components/common/EDropdownItem.vue')['default']
    EIcon: typeof import('./../components/common/EIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElementLayout: typeof import('./../layouts/ElementLayout/ElementLayout.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyPage: typeof import('./../components/page/EmptyPage.vue')['default']
    EPanelTitle: typeof import('./../components/page/AppPage/EPanelTitle.vue')['default']
    ErrorLayout: typeof import('./../layouts/ErrorLayout.vue')['default']
    MainHeader: typeof import('./../layouts/ElementLayout/MainHeader/MainHeader.vue')['default']
    MainHeaderDivider: typeof import('./../layouts/ElementLayout/MainHeader/MainHeaderUser/MainHeaderDivider.vue')['default']
    MainHeaderTabItem: typeof import('./../layouts/ElementLayout/MainHeader/MainHeaderTabs/MainHeaderTabItem.vue')['default']
    MainHeaderTabs: typeof import('./../layouts/ElementLayout/MainHeader/MainHeaderTabs/MainHeaderTabs.vue')['default']
    MainHeaderUser: typeof import('./../layouts/ElementLayout/MainHeader/MainHeaderUser/MainHeaderUser.vue')['default']
    MainHeaderUserAvatar: typeof import('./../layouts/ElementLayout/MainHeader/MainHeaderUser/MainHeaderUserAvatar.vue')['default']
    MainLayout: typeof import('./../layouts/MainLayout.vue')['default']
    MainMenu: typeof import('./../layouts/ElementLayout/MainMenu/MainMenu.vue')['default']
    PreviewLayout: typeof import('./../layouts/PreviewLayout.vue')['default']
    QuasarLayout: typeof import('./../layouts/QuasarLayout/QuasarLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterPage: typeof import('./../components/page/RouterPage.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
